apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx
      automountServiceAccountToken: false
      containers:
        - name: nginx
          image: nginx@sha256:295c7be079025306c4f1d65997fcf7adb411c88f139ad1d34b537164aa060369 #nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
              memory: 256m
            limits:
              cpu: 500m
              memory: 512m
          securityContext:
            capabilities:
              drop:
                - ALL
