name: lacework-iac-example-ga
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Scan the repo for vulnerabilities in IaC
        run: |
             echo $(pwd)
             env | grep "GITHUB_\|LW_\|CI_" > env.list
             echo "SCAN_COMMAND=tf-scan" >> env.list
             echo "WORKSPACE=src" >> env.list
             echo "EXIT_FLAG='Critical=1'" >> env.list 
             docker run --env-file env.list -v "$(pwd):/app/src" lacework/codesec-iac:latest
        env:
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
          LW_SUBACCOUNT: ${{ secrets.LW_SUBACCOUNT }}
          LW_API_KEY: ${{ secrets.LW_API_KEY }}
          LW_API_SECRET: ${{ secrets.LW_API_SECRET }}